modLoader="javafml"
loaderVersion="[41,)"
license="https://github.com/fonnymunkey/SimpleHatsAux/blob/main/LICENSE"
issueTrackerURL="https://github.com/fonnymunkey/SimpleHats/issues"
[[mods]]
  modId="simplehats"
  version="${file.jarVersion}"
  displayName="SimpleHats"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/simplehats"
  logoFile="logo.png"
  credits="Fonnymunkey - Coding, ArtsyDy - Textures/Models"
  authors="Fonnymunkey, ArtsyDy"
  description='''
  Simple, expandable, and user-customizable cosmetic hats mod.
  '''
  [[dependencies.simplehats]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.simplehats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.simplehats]]
    modId="curios"
    mandatory=true
    versionRange="[1.19-5.1.0.1,)"
    ordering="NONE"
    side="BOTH"